config/routes.rb
MoreEvolution::Application.routes.draw do

  resources :user_types

  resources :lifecycles

  get "pages/evolutions_home"
  get "pages/guide"
  
  match '/',  :to => 'pages#evolutions_home'

  resources :assignments
  resources :microposts
  resources :evolutions
  resources :opportunities
  devise_for :users
  resources :companies do
    resources :users, :assignments
  end
  resources :users do
    resources :companies, :assignments
  end

  
  
  

   root :to => 'pages#evolutions_home'

end

app/models/evolution.rb
class Evolution < ActiveRecord::Base
  attr_accessible :complete, :name, :opportunity_id, :user_id
  has_many :assignments
  has_many :opportunities, :through => :assignments
end

app/controllers/evolutions_controller.rb
class EvolutionsController < ApplicationController
  # GET /evolutions
  # GET /evolutions.json
  def index
    @evolutions = Evolution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @evolutions }
    end
  end

  # GET /evolutions/1
  # GET /evolutions/1.json
  def show
    @evolution = Evolution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evolution }
    end
  end

  # GET /evolutions/new
  # GET /evolutions/new.json
  def new
    @evolution = Evolution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evolution }
    end
  end

  # GET /evolutions/1/edit
  def edit
    @evolution = Evolution.find(params[:id])
  end

  # POST /evolutions
  # POST /evolutions.json
  def create
    @evolution = Evolution.new(params[:evolution])

    respond_to do |format|
      if @evolution.save
        format.html { redirect_to @evolution, notice: 'Evolution was successfully created.' }
        format.json { render json: @evolution, status: :created, location: @evolution }
      else
        format.html { render action: "new" }
        format.json { render json: @evolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /evolutions/1
  # PUT /evolutions/1.json
  def update
    @evolution = Evolution.find(params[:id])

    respond_to do |format|
      if @evolution.update_attributes(params[:evolution])
        format.html { redirect_to @evolution, notice: 'Evolution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evolutions/1
  # DELETE /evolutions/1.json
  def destroy
    @evolution = Evolution.find(params[:id])
    @evolution.destroy

    respond_to do |format|
      format.html { redirect_to evolutions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/evolutions_helper.rb
module EvolutionsHelper
end

app/views/evolutions/_form.html.erb
<%= form_for(@evolution) do |f| %>
  <% if @evolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evolution.errors.count, "error") %> prohibited this evolution from being saved:</h2>

      <ul>
      <% @evolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :opportunity_id %><br />
    <%= f.number_field :opportunity_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evolutions/edit.html.erb
<h1>Editing evolution</h1>

<%= render 'form' %>

<%= link_to 'Show', @evolution %> |
<%= link_to 'Back', evolutions_path %>

app/views/evolutions/index.html.erb
<h1>Listing evolutions</h1>

<table>
  <tr>
    <th>Opportunity</th>
    <th>Name</th>
    <th>User</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evolutions.each do |evolution| %>
  <tr>
    <td><%= evolution.opportunity_id %></td>
    <td><%= evolution.name %></td>
    <td><%= evolution.user_id %></td>
    <td><%= evolution.complete %></td>
    <td><%= link_to 'Show', evolution %></td>
    <td><%= link_to 'Edit', edit_evolution_path(evolution) %></td>
    <td><%= link_to 'Destroy', evolution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evolution', new_evolution_path %>

app/views/evolutions/new.html.erb
<h1>New evolution</h1>

<%= render 'form' %>

<%= link_to 'Back', evolutions_path %>

app/views/evolutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Opportunity:</b>
  <%= @evolution.opportunity_id %>
</p>

<p>
  <b>Name:</b>
  <%= @evolution.name %>
</p>

<p>
  <b>User:</b>
  <%= @evolution.user_id %>
</p>

<p>
  <b>Complete:</b>
  <%= @evolution.complete %>
</p>


<%= link_to 'Edit', edit_evolution_path(@evolution) %> |
<%= link_to 'Back', evolutions_path %>