config/routes.rb
MoreEvolution::Application.routes.draw do

  resources :user_types

  resources :lifecycles

  get "pages/evolutions_home"
  get "pages/guide"
  
  match '/',  :to => 'pages#evolutions_home'

  resources :assignments
  resources :microposts
  resources :evolutions
  resources :opportunities
  devise_for :users
  resources :companies do
    resources :users, :assignments
  end
  resources :users do
    resources :companies, :assignments
  end

  
  
  

   root :to => 'pages#evolutions_home'

end

app/models/lifecycle.rb
class Lifecycle < ActiveRecord::Base
  attr_accessible :description, :name, :rank
  has_many :assignments, :dependent => :destroy
  has_many :opportunities, :through => :assignments, :dependent => :destroy
end

app/controllers/lifecycles_controller.rb
class LifecyclesController < ApplicationController
  # GET /lifecycles
  # GET /lifecycles.json
  def index
    @lifecycles = Lifecycle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lifecycles }
    end
  end

  # GET /lifecycles/1
  # GET /lifecycles/1.json
  def show
    @lifecycle = Lifecycle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lifecycle }
    end
  end

  # GET /lifecycles/new
  # GET /lifecycles/new.json
  def new
    @lifecycle = Lifecycle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lifecycle }
    end
  end

  # GET /lifecycles/1/edit
  def edit
    @lifecycle = Lifecycle.find(params[:id])
  end

  # POST /lifecycles
  # POST /lifecycles.json
  def create
    @lifecycle = Lifecycle.new(params[:lifecycle])

    respond_to do |format|
      if @lifecycle.save
        format.html { redirect_to @lifecycle, notice: 'Lifecycle was successfully created.' }
        format.json { render json: @lifecycle, status: :created, location: @lifecycle }
      else
        format.html { render action: "new" }
        format.json { render json: @lifecycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lifecycles/1
  # PUT /lifecycles/1.json
  def update
    @lifecycle = Lifecycle.find(params[:id])

    respond_to do |format|
      if @lifecycle.update_attributes(params[:lifecycle])
        format.html { redirect_to @lifecycle, notice: 'Lifecycle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lifecycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lifecycles/1
  # DELETE /lifecycles/1.json
  def destroy
    @lifecycle = Lifecycle.find(params[:id])
    @lifecycle.destroy

    respond_to do |format|
      format.html { redirect_to lifecycles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lifecycles_helper.rb
module LifecyclesHelper
end

app/views/lifecycles/_form.html.erb
<%= form_for(@lifecycle) do |f| %>
  <% if @lifecycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lifecycle.errors.count, "error") %> prohibited this lifecycle from being saved:</h2>

      <ul>
      <% @lifecycle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lifecycles/edit.html.erb
<h1>Editing lifecycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @lifecycle %> |
<%= link_to 'Back', lifecycles_path %>

app/views/lifecycles/index.html.erb
<h1>Listing lifecycles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Rank</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lifecycles.each do |lifecycle| %>
  <tr>
    <td><%= lifecycle.name %></td>
    <td><%= lifecycle.description %></td>
    <td><%= lifecycle.rank %></td>
    <td><%= link_to 'Show', lifecycle %></td>
    <td><%= link_to 'Edit', edit_lifecycle_path(lifecycle) %></td>
    <td><%= link_to 'Destroy', lifecycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lifecycle', new_lifecycle_path %>

app/views/lifecycles/new.html.erb
<h1>New lifecycle</h1>

<%= render 'form' %>

<%= link_to 'Back', lifecycles_path %>

app/views/lifecycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lifecycle.name %>
</p>

<p>
  <b>Description:</b>
  <%= @lifecycle.description %>
</p>

<p>
  <b>Rank:</b>
  <%= @lifecycle.rank %>
</p>


<%= link_to 'Edit', edit_lifecycle_path(@lifecycle) %> |
<%= link_to 'Back', lifecycles_path %>